### ISSUE TITLE
Practica de GPS con Realidad Aumentada

### ISSUE THREAD

**Issue by ObedG** [SistemasTecTlaxiaco/practica-de-gps-equipo-obed#2]
[Reporte RA GPS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-gps-equipo-obed/files/6449291/Reporte.RA.GPS.pdf)

**Comment by ArteezyOne** [comment]
Calificación: 20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
